---
- name: Using loop, until, with_fileglob
  hosts: all
  become: yes
  tasks:
  - name: loop
    debug:
      msg: "Hello from {{item}}"
    loop:
      - "Me"
      - "World"
      
  - name: until
    shell: echo -n z>>file.txt && cat file.txt
    register: var1
    delay: 2
    retries: 10
    until: var1.stdout.find("zzzzz")==false
    notify: 
      - until_notify
      
  - name: with_fileglob
    vars:
      - dest_f: ./
      - source_f: ./
    copy: src={{ item }} dest={{ dest_f }}
    with_fileglob: "{{ source_f }}/*.*"
 
 
 
  handlers:
  - name: until_notify
    debug:
      var: var1

