---
- name: Install-nginx with block
  hosts: all
  become: yes
  vars:
    source_file: ./index.html
    dest_file: /var/www/html/
  tasks:
  - block: #for Debian
     - name: make apt update
       shell: cmd='sudo apt update'
     - name: install nginx
       apt: name=nginx state=latest
     - name: copy files to dir
       copy: src={{ source_file}} dest={{dest_file}}
       notify:
       - block_1
       - restart_nginx
     - name: start nginx
       service: name=nginx state=started enabled=yes
       notify:
       - block_1
    when: ansible_os_family=="Debian"
  handlers:
  - name: block_1
    shell: uptime
    register: results
    notify: link_1
  - name: link_1
    debug:
      var: results
  - name: restart_nginx
    service: name=nginx state=restarted


